apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  annotations:
    field.cattle.io/description: fleet at GitHub/dliebsterwb
  creationTimestamp: '2023-12-09T19:30:13Z'
  generation: 5
  managedFields:
    - apiVersion: fleet.cattle.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:desiredReadyClusters: {}
          f:display:
            .: {}
            f:readyBundleDeployments: {}
            f:state: {}
          f:lastSyncedImageScanTime: {}
          f:observedGeneration: {}
          f:readyClusters: {}
          f:resourceCounts:
            .: {}
            f:desiredReady: {}
            f:missing: {}
            f:modified: {}
            f:notReady: {}
            f:orphaned: {}
            f:ready: {}
            f:unknown: {}
            f:waitApplied: {}
          f:summary:
            .: {}
            f:desiredReady: {}
            f:ready: {}
      manager: fleetcontroller
      operation: Update
      subresource: status
      time: '2023-12-09T20:00:16Z'
    - apiVersion: fleet.cattle.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/description: {}
        f:spec:
          .: {}
          f:branch: {}
          f:clientSecretName: {}
          f:correctDrift:
            .: {}
            f:enabled: {}
          f:forceSyncGeneration: {}
          f:insecureSkipTLSVerify: {}
          f:paths: {}
          f:repo: {}
          f:targets: {}
      manager: rancher
      operation: Update
      time: '2023-12-09T20:00:16Z'
  name: dlwb-fleet
  namespace: fleet-default
  resourceVersion: '662877'
  uid: c0f03dab-c366-4617-836d-dd73517d3085
spec:
  branch: master
  clientSecretName: auth-tqzfw
  correctDrift:
    enabled: true
  forceSyncGeneration: 5
  insecureSkipTLSVerify: true
  paths: []
  repo: git@github.com:dliebsterwb/fleet.git
  targets:
    - clusterName: betty
status:
  conditions:
    - lastUpdateTime: '2023-12-09T19:30:13Z'
      status: 'True'
      type: Ready
    - lastUpdateTime: '2023-12-09T20:00:16Z'
      status: 'True'
      type: Accepted
    - lastUpdateTime: '2023-12-09T19:30:13Z'
      status: 'True'
      type: ImageSynced
    - lastUpdateTime: '2023-12-09T19:30:14Z'
      status: 'False'
      type: Reconciling
    - lastUpdateTime: '2023-12-09T19:47:34Z'
      message: commit not found
      reason: Stalled
      status: 'True'
      type: Stalled
    - lastUpdateTime: '2023-12-09T19:47:34Z'
      status: 'True'
      type: Synced
  desiredReadyClusters: 0
  display:
    readyBundleDeployments: 0/0
    state: GitUpdating
  lastSyncedImageScanTime: null
  observedGeneration: 5
  readyClusters: 0
  resourceCounts:
    desiredReady: 0
    missing: 0
    modified: 0
    notReady: 0
    orphaned: 0
    ready: 0
    unknown: 0
    waitApplied: 0
  summary:
    desiredReady: 0
    ready: 0
